### ISSUE TITLE
Security camera control, accessible remotely

### ISSUE THREAD

**Issue by robogeek** [robogeek/techsparx-research#14]
When away from home, many people leave security cameras in their home, which they can view remotely.  The idea is sound - video of a home along with automatic motion detection can give a warning about intruders or other problems.  One can then view the home from anywhere.

There are many "security camera" products that fill this niche.  Typically the camera video feed is sent over the Internet to a service operated by the camera manufacturer.  Who knows what happens to the video from there?  Can miscreants access the video?

In other words, it's best to have control over the video, to have an in-home video archive, and for the video to not be sent outside the home network.

Another aspect is - many of these cameras connect over WiFi or Ethernet and the video is sent as a video protocol like RTSP.

# Videos

https://www.youtube.com/watch?v=l3f7K7L6o8E -- Haven't watched it.  I suspect this is a project using Raspberry Pi Zero W, the Raspberry Pi camera, and motion sensors, to send a RTSP stream over the WiFi network.  At least, that's what I would do if I were to build a surveillance camera from scratch.  I'd also add IR illumination and use the no-IR version of the Raspberry Pi camera.

https://www.youtube.com/watch?v=6ahtCpIoWU4 -- Demonstration of using REOLink cameras along with Viseron.  These cameras support in-camera storage on up to 512GB MicroSD cards, and support at least RTSP streaming.  I think they have built-in IR.  Quite capable cameras at a very reasonable price.  Most of the video is the physical installation in a typical suburban house.  Another large segment is Viseron.  Brief mention of integrating these cameras with Home Assistant.

https://www.youtube.com/watch?v=3i9aRwjYQt0 -- Another video about REOLink cameras.  In this case it shows the REOLink NVR solution.

https://www.youtube.com/watch?v=NzbghOfRx3k -- Shows using the Frigate NVR solution along with Coral AI for beefing up automatic image/object recognition on a NAS running TrueNAS.

# NVR software

NVR == Network Video Recorder (I think)

Years ago I used MotionEyeOS on a Raspberry Pi.  It was cool and easy to install.  But, the guy behind it is no longer supporting it.  https://github.com/motioneye-project/motioneyeos

It's likely that MotionEyeOS is based on MotionEye - https://github.com/motioneye-project/motioneye - which is itself a wrapper around the Motion project - https://motion-project.github.io/index.html - The latter is video recording from video cameras and other stuff.

Sentryshot - https://github.com/SentryShot/sentryshot/tree/master - https://codeberg.org/SentryShot/sentryshot - System for recording video from cameras.

ZoneMinder - https://zoneminder.readthedocs.io/en/latest/index.html - Described as an all-in-one solution for security cameras.  Going by its documentation it's feature-filled.  I tried installing the Docker container - https://hub.docker.com/r/dlandon/zoneminder - and it was more than difficult.  What should be simpler is to in a Lima virtual machine follow the instructions for installation with apt-get.  The Docker image was difficult to find and doesn't seem to be a priority.  Further, every time I launched the Docker image it went through a lengthy setup process installing a bunch of packages via apt-get which took 10+ minutes.  That's not the way Docker images should behave.

https://wiki.zoneminder.com/Dummies_Guide -- This is supposed to be a "For Dummies" guide for using ZoneMinder

https://github.com/scottlamb/moonfire-nvr -- I think this belongs on a "not recommended" list.  It records video as individual frames as JPEG allowing them to construct MP4 files from any arbitrary time range, which is a cool idea, that would obviously consume lots of inodes.  It lacks motion detection and other important features.  HARD PASS.

Viseron -- https://viseron.netlify.app/ -- One of the videos above goes over this tool.  It looks simple to set up, and appears well supported for Docker installation.  HIGHLY RECOMMENDED

https://frigate.video/ -- Frigate NVR -- Good features -- integrates with AI chips for object detection -- advanced video processing features -- but apparently difficult to setup.

# Cameras

https://www.amazon.de/-/en/TP-Link-Tapo-C200-Camera-Resolution/dp/B07XLML2YS/ref=sr_1_4 -- TP-Link has many security cameras, of which this is one example.  I believe TP-Link has a cloud-based remote monitoring system.  I believe TP-Link is Chinese which automatically raises security concerns.  But, this device is inexpensive and has many interesting features.  I'm sure it provides RTSP streaming.

https://www.amazon.de/Reolink-Surveillance-Detection-Waterproof-RLC-810A/dp/B08F7C37NZ/ref=sxin_15_pa_sp_search_thematic_sspa  -- ReoLink is highly recommended in two of the above videos.  It supports RTSP streaming to local services, has built-in video storage in the camera, built-in object detection etc in the camera, the camera can connect over ethernet, power over ethernet, IR support, etc.  The above videos demonstrate their own NVR solution, as well as integration with Viseron or HomeAssistant.

https://www.amazon.de/AOBOCAM-Surveillance-Transmission-Battery-Compact/dp/B0D6W6G1T6/ref=sxin_15_pa_sp_search_thematic_sspa -- Generic junk Chinese micro-sized camera.  I suppose it'll simply do RTSP over WiFi with no cloud system.  Inexpensive.

https://www.amazon.de/-/en/Codnida-Outdoor-Surveillance-Automatic-Tracking/dp/B0BPH1L3N4/ref=sr_1_7  -- Likely another generic Chinese product.  High resolution camera, IR, IR illumination, speaker and microphone to talk with people, floodlight, siren, etc.

Amazon search:  https://www.amazon.de/-/en/Surveillance-Cameras/b/ref=dp_bc_5?ie=UTF8&node=119915031

**Comment by robogeek** [comment]
https://www.home-assistant.io/integrations/generic/ -- Discusses how Home Assistant can consume video feeds from RTSP

**Comment by robogeek** [comment]
https://www.home-assistant.io/integrations/agent_dvr/ - Home Assistant integration with Agent DVR

https://www.ispyconnect.com/ -- Agent DVR is commercial software but is free for personal use and seems to have good features

**Comment by robogeek** [comment]
https://www.home-assistant.io/integrations/camera.ffmpeg/ - Integration with an FFMPEG source

**Comment by robogeek** [comment]
https://www.home-assistant.io/integrations/#camera -- Many other camera integrations

**Comment by robogeek** [comment]
On laptop, installed Viseron intending to use the laptop webcam, using this Compose file

```yaml
services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    shm_size: "1024mb"
    volumes:
      - /home/david/Projects/docker/viseron/segments:/segments
      - /home/david/Projects/docker/viseron/snapshots:/snapshots
      - /home/david/Projects/docker/viseron/thumbnails:/thumbnails
      - /home/david/Projects/docker/viseron/events:/event_clips
      - /home/david/Projects/docker/viseron/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    # devices:
    #   - /dev/dri
    # networks:
    #   - servernet
    environment:
      - PUID=1000
      - PGID=1000

# networks:
#     servernet:
#         external: true

```

A similar Compose file on davidnuc1 is installed 

Viseron starts easily enough, and the config directory gets a `config.yml`.  There is a camera section with two items that need to be filled in.

The Camera "domain" describes using ffmpeg or gstreamer -- https://viseron.netlify.app/components-explorer?tags=camera

Reading - https://github.com/roflcoopter/viseron/discussions/705 - about using a local USB camera. -- ALSO -- https://github.com/roflcoopter/viseron/issues/708

So.. there needs to be a raw ffmpeg command that knows the local /dev/xxx for the video

https://unix.stackexchange.com/questions/670406/how-can-i-find-the-usb-devices-camera

Command: `v4l2-ctl --list-devices`

On Ubuntu this required:

```shell
$ v4l2-ctl --list-devices
Command 'v4l2-ctl' not found, but can be installed with:
sudo apt install v4l-utils
$ sudo apt-get install v4l-utils
```

Which gave

```shell
$ v4l2-ctl --list-devices
Iriun Webcam (platform:v4l2loopback-000):
	/dev/video0

Integrated_Webcam_HD: Integrate (usb-0000:00:1d.0-1.6):
	/dev/video1
	/dev/video2
	/dev/media0

## THIS THEN GAVE INTERESTING OUTPUT
$ ffplay -f video4linux2 -list_formats all /dev/video1
$ ffplay -f video4linux2 -list_formats all /dev/video2
```


Using the sources above, I added this to the config file

```yaml
    camera_1:
      name: bird bath webcam
      host: 111.111.111.111
      port: 1111
      path: /dev/video6
      width: 1280
      height: 720
      fps: 10
      codec: libx264 
      audio_codec: opus
      # raw_command: ffmpeg -f video4linux2 -video_size 1280x720 -framerate 10 -i /dev/video1 -c:v libx264 -preset ultrafast -tune zerolatency -f rawvideo -pix_fmt nv12 pipe:1
      raw_command: ffmpeg -f video4linux2 -i /dev/video1 -f rawvideo -pix_fmt nv12 pipe:1

```

The ownership of that file is root:video

With the user/group id set to 1000 this resulted in a permissions error.

Removing that user/group - Viseron now see's video.  But it's at a very low frame rate and the video is messed up.  But it's video.

**Comment by robogeek** [comment]
Scrypted -- Can connect almost any camera to almost any "home hub" -- https://www.youtube.com/watch?v=x1xsFRQYSv0

https://www.scrypted.app/

Their camera buying guide is interesting: https://docs.scrypted.app/buyers-guide/cameras.html

```yaml
# The Scrypted docker-compose.yml file typically resides at:
# ~/.scrypted/docker-compose.yml


# Scrypted NVR Storage (Optional Network Volume: Part 1 of 3)
# Example volumes SMB (CIFS) and NFS.
# Uncomment only one.
# volumes:
#     nvr:
#         driver_opts:
#             type: cifs
#             o: username=[username],password=[password],vers=3.0,file_mode=0777,dir_mode=0777 
#             device: //[ip-address]/[path-to-directory]
#     nvr:
#         driver_opts:
#             type: "nfs"
#             o: "addr=[ip-address],nolock,soft,rw"
#             device: ":[path-to-directory]"

services:
    scrypted:
        # LXC usage only
        # lxc privileged: true

        environment:
            # Scrypted NVR Storage (Part 2 of 3)

            # Uncomment the next line to configure the NVR plugin to store recordings
            # use the /nvr directory within the container. This can also be configured
            # within the plugin manually.
            # The drive or network share will ALSO need to be configured in the volumes
           # section below.
            - SCRYPTED_NVR_VOLUME=/nvr

            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer ${WATCHTOWER_HTTP_API_TOKEN:-env_missing_fallback}
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update

            # LXC usage only
            # lxc - SCRYPTED_INSTALL_ENVIRONMENT=lxc-docker

            # Avahi can be used for network discovery by passing in the host daemon
            # or running the daemon inside the container. Choose one or the other.
            # Uncomment next line to run avahi-daemon inside the container.
            # See volumes and security_opt section below to use the host daemon.
            # - SCRYPTED_DOCKER_AVAHI=true

        # NVIDIA (Part 1 of 2)
        # runtime: nvidia

        # NVIDIA (Part 2 of 2) - Use NVIDIA image, and remove subsequent default image.
        # image: ghcr.io/koush/scrypted:nvidia
        image: ghcr.io/koush/scrypted

        volumes:
            # Scrypted NVR Storage (Part 3 of 3)

            # Modify to add the additional volume for Scrypted NVR.
            # The following example would mount the /mnt/media/video path on the host
            # to the /nvr path inside the docker container.
            # - /mnt/media/video:/nvr
            - /home/david/Projects/docker/scrypted/nvr:/nvr

            # Or use a network mount from one of the CIFS/NFS examples at the top of this file.
            # - type: volume
            #   source: nvr
            #   target: /nvr
            #   volume:
            #     nocopy: true

            # Uncomment the following lines to use Avahi daemon from the host.
            # Ensure Avahi is running on the host machine:
            # It can be installed with: sudo apt-get install avahi-daemon
            # This is not compatible with running avahi inside the container (see above).
            # Also, uncomment the lines under security_opt
            - /var/run/dbus:/var/run/dbus
            - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

            # Default volume for the Scrypted database. Typically should not be changed.
            # The volume will be placed relative to this docker-compose.yml.
            - ./volume:/server/volume

            # LXC usage only
            # lxc - /var/run/docker.sock:/var/run/docker.sock
            # lxc - /root/.scrypted/docker-compose.yml:/root/.scrypted/docker-compose.yml
            # lxc - /root/.scrypted/docker-compose.sh:/root/.scrypted/docker-compose.sh
            # lxc - /root/.scrypted/.env:/root/.scrypted/.env
            # lxc - /mnt:/mnt
       # Uncomment the following lines to use Avahi daemon from the host
        # Without this, AppArmor will block the container's attempt to talk to Avahi via dbus
        security_opt:
            - apparmor:unconfined
        devices: [
            # uncomment the common systems devices to pass
            # them through to docker.

            # all usb devices, such as coral tpu
            "/dev/bus/usb:/dev/bus/usb",

            # hardware accelerated video decoding, opencl, etc.
            # "/dev/dri:/dev/dri",

            # AMD GPU
            # "/dev/kfd:/dev/kfd",

            # uncomment below as necessary.
            # zwave usb serial device

            # "/dev/ttyACM0:/dev/ttyACM0",

            # coral PCI devices
            # "/dev/apex_0:/dev/apex_0",
            # "/dev/apex_1:/dev/apex_1",
        ]
        container_name: scrypted
        restart: unless-stopped
        network_mode: host

        # logging is noisy and will unnecessarily wear on flash storage.
        # scrypted has per device in memory logging that is preferred.
        # enable the log file if enhanced debugging is necessary.
        logging:
            driver: "none"
            # driver: "json-file"
            # options:
            #     max-size: "10m"
            #     max-file: "10"
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
    # watchtower manages updates for Scrypted.
    watchtower:
        environment:
            - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN:-env_missing_fallback}
            - WATCHTOWER_HTTP_API_UPDATE=true
            - WATCHTOWER_SCOPE=scrypted
            - WATCHTOWER_HTTP_API_PERIODIC_POLLS=${WATCHTOWER_HTTP_API_PERIODIC_POLLS:-true}
        image: containrrr/watchtower
        container_name: scrypted-watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "com.centurylinklabs.watchtower.scope=scrypted"
        ports:
            # The auto update port 10444 can be configured
            # Must match the port in the auto update url above.
            - 10444:8080
        # check for updates once an hour (interval is in seconds)
        command: --interval 3600 --cleanup --scope scrypted
```

**Comment by robogeek** [comment]
Using FFMPEG to stream the laptop USB webcam

```
$ ffmpeg -video_size 1280x720 -framerate 30 -f v4l2 -i /dev/videoN

...
[video4linux2,v4l2 @ 0x57c13bae40c0] The V4L2 driver changed the video from 1280x720 to 640x480
Input #0, video4linux2,v4l2, from '/dev/video1':
  Duration: N/A, start: 467816.600796, bitrate: 147456 kb/s
  Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 640x480, 147456 kb/s, 30 fps, 30 tbr, 1000k tbn
At least one output file must be specified
[video4linux2,v4l2 @ 0x57c13bae40c0] Some buffers are still owned by the caller on close.
ioctl(VIDIOC_QBUF): Bad file descriptor

```

Neglected to give the output file

```
$ ffmpeg -video_size 1280x720 -framerate 30 -f v4l2 -i /dev/videoN -pix_fmt yuv420p -crf 30 video.mp4
```

This worked fairly well.  It does not have audio.  Because the room is dark, the video is grainy.

https://www.youtube.com/watch?v=sbpeFdVjZqw

**Comment by robogeek** [comment]
https://cooper-davis.net/blog/viseron-and-the-tapo-c310 -- Using Viseron to display video from a TP-Link IP camera using RTSP streaming

```yaml
## Cameras
ffmpeg:
  camera:
    hillview_front:

      ### Recording stream
      name: Tapo C310
      host: cameras.local.ip.address
      port: 554
      path: /stream1/
      username: username_set_in_tapo_app
      password: password_set_in_tapo_app

      audio_codec: aac
      codec: h264
      fps: 15
      width: 2304
      height: 1296

      ### Low-res stream
      substream:
        path: /stream2/
        port: 554

        audio_codec: aac
        codec: h264
        fps: 15
        width: 640
        height: 360

      recorder:
        lookback: 20
        extension: mp4

## Motion detectors
background_subtractor:
  motion_detector:
    cameras:

      hillview_front:
        width: 320
        height: 180

        trigger_recorder: true
        fps: 1
        area: 0.01
        threshold: 15
        alpha: 0.1

## NVR
nvr:
  hillview_front:
```

**Comment by robogeek** [comment]
Multiple methods to publish RTSP streams -- https://stackoverflow.com/questions/26999595/what-steps-are-needed-to-stream-rtsp-from-ffmpeg

https://trac.ffmpeg.org/wiki/ffserver -- ffserver is interesting, but is it kept up-to-date?  There's a Docker image for it that hasn't been updated for 6 years

Mentioned is rtsp-simple-server ... however, that has been changed to MediaMTX -- https://github.com/bluenviron/mediamtx?tab=readme-ov-file#basic-usage

https://hub.docker.com/r/bluenviron/mediamtx -- Docker image

What I learned from these is ... use ffmpeg to publish RTSP to a streaming server, then the streaming server publishes to the world.  The ffserver page has a nice graphic for this.

https://coderslegacy.com/ffmpeg-rtsp-streaming/ -- This seems like a simple introduction to MediaMTX but the instructions do not work

**Comment by robogeek** [comment]
gstreamer -- https://gstreamer.freedesktop.org/

https://gstreamer.freedesktop.org/documentation/?gi-language=c

**Comment by robogeek** [comment]
https://www.youtube.com/watch?v=qenAQwLvZfA -- walkthrough of setting up an RTMP server using NGINX and FFMPEG

No external dependencies

Don't know where to retrieve the sample code but there's not much to it.

**Comment by robogeek** [comment]
Setting up a ReoLink E340 on Viseron using the above Compose file.

First is setting up the camera on the home WiFi.

1. Install the ReoLink software on smart phone.
2. Use the app to scan the QR code on the bottom of the camera
3. Fun that the camera starts talking to me because why not there's a speaker
4. Scanning the QR code started a wizard
5. At one point - it wants to add WiFi network credentials.  Make sure to add everything - the security password for example.  The camera will scan the screen of the smart phone when a QR is shown, and it seems the QR must be including WiFi network characteristics
6. If all goes well the camera will tell you it is set up

Head over to your router dashboard and see what IP address it assigned.  This will be a dynamically assigned address via DHCP.  If your router can assign a static IP address then do so in the router.  To construct the RTSP or RTMP URL we need a fixed IP address.

It's also possible to assign a fixed IP address in the ReoLink web app that runs from the camera.  We'll talk about this later.

Streaming over RTSP: https://support.reolink.com/hc/en-us/articles/900000630706-Introduction-to-RTSP/?slug=stream&search=rtmp

The format of the RTSP URL is: `rtsp://<username>:<password>@<IP address>/Preview_<channel number>_<stream type>`

https://support.reolink.com/hc/en-us/articles/23528840063769-Introduction-to-Real-Time-Messaging-Protocol-RTMP/?slug=stream&search=rtmp

The ReoLink smart phone app doesn't provide enough information nor offer as much configuration options.  It's useful for monitoring while on the go.

The ReoLink app thingy available via desktop web browsers is much more useful.  Go to `http://IP-ADDRESS/` to access this app thingy.

The "channel number" is available in the stream that plays on the home page.

The main page has a number of settings panes on the right that are useful.

Useful details are available at the Gear Icon

Click on Network.  It shows the summary of the network configuration.  Click on Set Up - and you can change things.  If your router was unable to set a static IP address in the DHCP area - you can statically assign an IP address here.

Next, expand the button that says _Advanced_.  Click on the _Server Settings_ button.

For streaming to 3rd party apps - enable either RTSP or RTMP

If you want, enable HTTPS and/or HTTP

Between the URL format for RTSP and the Network information in this app we can now access the live stream from a 3rd party app.

Start by installing and using VLC.  This is available via every package management system - and info is at https://www.videolan.org/.  e.g. for Ubuntu: `sudo apt-get install vlc` .. for MacPorts: `sudo port install vlc`

In VLC - use File > Open Network Stream.  In the window that pops up, enter your RTSP or RTMP URL.  It should come up and play.  It unfortunately does not give useful info for debugging.

For RTSP - `rtsp://admin:PASSWORD@192.168.8.110/Preview_01_main`

For Viseron, in `config/config.yaml`, enter:

```yaml
    camera_1:
      name: MDWatcher - ReoLink E340
      host: 192.168.8.110
      port: 554
      path: Preview_01_main
      username: admin
      password: 'PASSWORD'

darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

mog2:
  motion_detector:
    cameras:
      camera_2:  # Attach detector to the configured camera_2 above
        fps: 1

nvr:
  camera_1:  # Run NVR for camera_1

```

The video should come up correctly with these settings.  But, performance is not good.

This relies on a lot of defaults.  The ReoLink support pages give a lot of info on video formats etc.  This can be configured into the Viseron config file.
