### ISSUE TITLE
Setting up RustDesk

### ISSUE THREAD

**Issue by robogeek** [robogeek/techsparx-research#22]
Rust Desk - https://rustdesk.com/ - is screen sharing software meaning one can access the desktop session of another computer.  All the reviews of this software are excellent.  Looking at review videos it seems that it can even handle the login screen - something that VNC Is incapable of handling.

There are three modes:

1. LAN only (local computers)
2. Access server hosted outside the LAN, allowing access to LAN resources from outside the LAN
3. Access server hosted inside the LAN, allowing access to LAN resources from outside the LAN.

This is the Compose file I'm using:

```yaml
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - /home/david/docker/rust/data:/root
    network_mode: "host"
    # ports:
    #   - 21115:21115
    #   - 21116:21116
    #   - 21116:21116/udp
    #   - 21118:21118
    depends_on:
      - hbbr
    restart: unless-stopped
    # networks:
    #   - servernet

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - /home/david/docker/rust/data:/root
    network_mode: "host"
    # ports
    #   - 21117:21117
    #   - 21119:21119
    restart: unless-stopped
    # networks:
    #   - servernet

# networks:
#     servernet:
#         external: true
```

The Open Source is Awesome review - https://www.youtube.com/watch?v=9nzHm3xGz2I -- showed a Compose file with the `ports` declarations shown here.

However, the RustDesk team suggests this - 
https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/:

```yaml
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
```

I put those in because I wanted to do my normal thing of associating the ports with a domain name and to put this behind the Caddy server.  Then I realized the ports in question are not going to be HTTP but some video protocol.  Searching for "hosting rustdesk behind Caddy proxy" turned up discussions about how difficult it is to run Rustdesk behind Caddy.  Difficult === Impossible, actually.  One discussed a Caddy extension for proxying other protocols, but that's more than I want to take care of.

The `network-mode: host` setting means all the ports are in the host port space and that's that, no possibility of using Caddy in such a mode.

On Ubuntu, this means to run the following

```shell
$ sudo ufw 21115 allow
...
```

This ensures that traffic can go in/out of the server machine

Then, the router firewall rules must be updated to support these ports:

![Image](https://github.com/user-attachments/assets/f6c1afcb-65ab-4172-9841-088b80c01612)

A domain name must point to the HomeInternetRouter.  For most this means using a dynamic DNS service.  In my case the ISP for our apartment gives us a fixed IP address, and further lets us assign a domain name to our internet connection.

Once a domain name is reliably assigned to the internet connection, meaning that for dynamic IP address assignment the domain name A/AAAA record(s) reliably change to match, then additional domain names are assigned for each hosted service.  That means `git.example.com` for Gitea, `cloud.example.com` for NextCloud, and so on.

# Setting up the Rustdesk client

This is out of order.  The client should be setup first.

Download the client app for your platform from the RustDesk website.  I don't understand why this is not in the package distribution systems.

Carefully read the instructions for each because it's not entirely clear.

For macOS - https://rustdesk.com/docs/en/client/mac/ - the pictures of the Settings to change do not match current macOS (Sequoia).  When the application is first executed it will invoke some settings changes automatically.  It's good afterward to review those changes and make sure everything makes sense.

It's clear that RustDesk requires permission to access the video/screen, mouse, keyboard, sound, etc ... and most of the settings changes are those permissions.

The RustDesk settings are accessed by the three-vertical-dots button next to the ID.  That button takes one immediately to the Settings area.

For some RustDesk settings panes you must click on Unlock button before you can make changes.  This button is at the top of the pane.  I missed it.

In _Security_, click on _Change ID_ 

In Network, unlock it, and click on ID/Relay server -- change the ID server field to be the domain name with which to reach the ID server

For Linux it's approximately the same and the user interface is the same between them.

I think this review - https://www.youtube.com/watch?v=x9A7MuAvDlQ - shows editing a config file to make the login session be in X11 mode because RustDesk cannot handle the Wayland login screen.  However - https://rustdesk.com/docs/en/client/linux/ - now says there is experimental Wayland support.

The Linux page - https://rustdesk.com/docs/en/client/linux/ - does discuss which file to edit to use X11 login rather than Wayland login.

# Using an Auth server

On the home screen of the application is an indicator whether it is connected to an auth server.

With the Docker container setup etc as discussed above, this indicator should be a green dot with the word Ready

According to the review videos it should be a matter of entering the ID code for the target machine in the "Control Remote Desktop" box, then click Connect.

But, I get "_Connection Error_" and "_key mismatch_".

I found this as a clear solution: https://github.com/rustdesk/rustdesk/issues/499#issuecomment-1160578895

Referred from: https://github.com/rustdesk/rustdesk/discussions/1418#discussioncomment-3543238

This solution says to make sure the `id_ed25519` files are the same security certificates in both `hbbr` and `hbbs`.  Look at the Compose file and you see the `/root` in both containers come from the same directory.  Ergo the two files are identical because they're the same file.

In the "clear solution" it says the keys must be the same.  The installation page - https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/install/ - concurs

https://www.youtube.com/watch?v=PjY5TpWMNz4 - This video goes over setup on a QNAP server using Docker
  There is a Compose file at https://gist.github.com/shivan/b76819d85e0dc9c3c12faab94021fa68

This Compose file has two different volumes, one for `hbbr` (the relay server) and `hbbs` (the server).  

I changed my Compose file to use two directories.  On restarting the server, files were generated into one directory but not the other.  After reading the discussion above, I copied the id files over to the other directory.  But this did not change the behavior.

There's also something in the discussions about copying keys into the security section.

Indeed, on https://rustdesk.com/docs/en/self-host/client-configuration/ it says to copy the public key into the network configuration in the client.

Once the public key was copied into the clients then I could use either to connect with the other computer.

https://www.youtube.com/watch?v=LxhfBHh3_AQ - This video promises to be a complete introduction to installing and configuring RustDesk - but it's actually very weak.

It's nice that the video has clearly defined Actors (as a UML term) along with Use Cases for those actors.

But, the setup of the relay server is woefully inadequate.
