### ISSUE TITLE
Nextcloud FPM implementation - behind NGINX Proxy Manager - or behind Caddy

### ISSUE THREAD

**Issue by robogeek** [robogeek/techsparx-research#7]
NextCloud users of course want better performance.  Typically it is a sluggish user experience.

The documentation for Nextcloud performance improvements says to use FPM.

https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html  -- Actually that is not quite accurate.  There are a number of steps to attempt such as OPCACHE tuning.

In any case, the README for the NextCloud container https://github.com/docker-library/docs/blob/master/nextcloud/README.md, when discussing FPM, refers to the Docker Compose discussion which offers the following:

```yaml
volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
```

With my current deployment - NGINX Proxy Manager handles proxying for the services.  So... can IT handle the FPM portion of this.

Unfortunately - the N.P.M. configuration screens do not offer a simple way of configuring FPM.  There is no magic button for that task.  Instead the only tool available is the Advanced Configuration screen.

In the N.P.M. issue queue -- BTW, well over 1200 open issues is not a good sign -- there are a few showing up searching for FPM.  Such as: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3850

Other people, in other words, are asking similar questions.  (Configuring FPM on NGINX Proxy Manager)

There is quite a lot of commit activity in the N.P.M. repository, so it's not that this is a dead project.

On the other hand, Caddy ... has direct support ... perhaps better?  https://caddyserver.com/

https://caddyserver.com/docs/caddyfile/directives/php_fastcgi
